#ifndef CONFIG_DERUI_H
#define CONFIG_DERUI_H

#undef MOUSEKEY_ENABLE
#undef LOCKING_RESYNC_ENABLE
#undef RGBLIGHT_ENABLE

#include QMK_KEYBOARD_CONFIG_H

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 300

#undef TAPPING_TERM
#define TAPPING_TERM 150

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 1000

#endif
